#IMPORT LIBRARIES

In [1]:
import requests
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt
import os

#DATA COLLECTION

In [2]:
DATASET_URI = "https://raw.githubusercontent.com/KLGLUG/student-career-area-prediction-using-machine-learning/master/Project%20Code/roo_data.csv"

open("./dataset.csv", "wb").write(requests.get(DATASET_URI).content)
print("Dataset downloaded.")

Dataset downloaded.


#DATA PREPROCESSING

In [3]:
dataset = pd.read_csv("./dataset.csv")
dataset.head()

Acedamic percentage in Operating Systems  percentage in Algorithms  \
0                                        69                        63   
1                                        78                        62   
2                                        71                        86   
3                                        76                        87   
4                                        92                        62   

   Percentage in Programming Concepts  Percentage in Software Engineering  \
0                                  78                                  87   
1                                  73                                  60   
2                                  91                                  87   
3                                  60                                  84   
4                                  90                                  67   

   Percentage in Computer Networks  Percentage in Electronics Subjects  \
0                               94                                  94   
1                               71                                  70   
2                               61                                  81   
3                               89                                  73   
4                               71                                  89   

   Percentage in Computer Architecture  Percentage in Mathematics  \
0                                   87                         84   
1                                   73                         84   
2                                   72                         72   
3                                   62                         88   
4                                   73                         71   

   Percentage in Communication skills  Hours working per day  ...  \
0                                  61                      9  ...   
1                                  91                     12  ...   
2                                  94                     11  ...   
3                                  69                      7  ...   
4                                  73                      4  ...   

   Interested Type of Books  Salary Range Expected  In a Realtionship?  \
0              Prayer books                 salary                  no   
1                 Childrens                 salary                 yes   
2                    Travel                   Work                  no   
3                   Romance                   Work                 yes   
4                 Cookbooks                 salary                  no   

   Gentle or Tuff behaviour? Management or Technical Salary/work  \
0                   stubborn              Management      salary   
1                     gentle               Technical      salary   
2                   stubborn              Management        work   
3                     gentle              Management        work   
4                   stubborn              Management        work   

  hard/smart worker worked in teams ever? Introvert  \
0       hard worker                   yes        no   
1       hard worker                    no       yes   
2       hard worker                    no       yes   
3      smart worker                   yes       yes   
4       hard worker                   yes       yes   

               Suggested Job Role  
0              Database Developer  
1            Portal Administrator  
2            Portal Administrator  
3  Systems Security Administrator  
4        Business Systems Analyst  

[5 rows x 39 columns]

In [7]:
labels = dataset['Suggested Job Role'].unique()

In [12]:
label_list = labels.tolist()

In [13]:
label_list

['Database Developer',
 'Portal Administrator',
 'Systems Security Administrator',
 'Business Systems Analyst',
 'Software Systems Engineer',
 'Business Intelligence Analyst',
 'CRM Technical Developer',
 'Mobile Applications Developer',
 'UX Designer',
 'Quality Assurance Associate',
 'Web Developer',
 'Information Security Analyst',
 'CRM Business Analyst',
 'Technical Support',
 'Project Manager',
 'Information Technology Manager',
 'Programmer Analyst',
 'Design & UX',
 'Solutions Architect',
 'Systems Analyst',
 'Network Security Administrator',
 'Data Architect',
 'Software Developer',
 'E-Commerce Analyst',
 'Technical Services/Help Desk/Tech Support',
 'Information Technology Auditor',
 'Database Manager',
 'Applications Developer',
 'Database Administrator',
 'Network Engineer',
 'Software Engineer',
 'Technical Engineer',
 'Network Security Engineer',
 'Software Quality Assurance (QA) / Testing']

In [14]:
dataset['Suggested Job Role'] = dataset['Suggested Job Role'].apply(lambda x: label_list.index(x))

In [16]:
data = dataset.iloc[:,:-1].values
label = dataset.iloc[:,-1].values
len(data[0]) # 38 columns

38

In [17]:
len(label)

20000

### One Hot Encoding

In [18]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [19]:
labelencoder = LabelEncoder()

In [20]:
for i in range(14,38):
  data[:,i] = labelencoder.fit_transform(data[:,i])

data[:5]

array([[69, 63, 78, 87, 94, 94, 87, 84, 61, 9, 4, 0, 4, 8, 1, 1, 1, 8, 0,
        0, 1, 0, 0, 4, 4, 0, 8, 0, 0, 21, 1, 0, 1, 0, 0, 0, 1, 0],
       [78, 62, 73, 60, 71, 70, 73, 84, 91, 12, 7, 1, 2, 3, 1, 0, 1, 5,
        2, 0, 0, 2, 1, 7, 0, 1, 4, 1, 1, 5, 1, 1, 0, 1, 0, 0, 0, 1],
       [71, 86, 91, 87, 61, 81, 72, 72, 94, 11, 1, 4, 1, 3, 1, 0, 1, 0,
        7, 0, 1, 2, 0, 6, 2, 0, 5, 1, 1, 29, 0, 0, 1, 0, 1, 0, 0, 1],
       [76, 87, 60, 84, 89, 73, 62, 88, 69, 7, 1, 1, 2, 5, 0, 1, 0, 6, 1,
        1, 0, 1, 0, 7, 5, 0, 7, 0, 0, 23, 0, 1, 0, 0, 1, 1, 1, 1],
       [92, 62, 90, 67, 71, 89, 73, 71, 73, 4, 5, 4, 6, 3, 0, 0, 0, 0, 0,
        0, 0, 2, 0, 0, 5, 0, 9, 0, 1, 7, 1, 0, 1, 0, 1, 0, 1, 1]],
      dtype=object)

In [21]:
from sklearn.preprocessing import Normalizer

In [22]:
data1 = data[:,:14]

In [23]:
normalized_data = Normalizer().fit_transform(data1)
normalized_data.shape

(20000, 14)

In [24]:
data2 = data[:, 14:]
data2.shape

(20000, 24)

In [25]:
df1 = np.append(normalized_data, data2, axis=1)
df1.shape

(20000, 38)

## Adding readable headers

In [26]:
headers = ['Acedamic percentage in Operating Systems', 'percentage in Algorithms',
       'Percentage in Programming Concepts',
       'Percentage in Software Engineering', 'Percentage in Computer Networks',
       'Percentage in Electronics Subjects',
       'Percentage in Computer Architecture', 'Percentage in Mathematics',
       'Percentage in Communication skills', 'Hours working per day',
       'Logical quotient rating', 'hackathons', 'coding skills rating',
       'public speaking points', 'can work long time before system?',
       'self-learning capability?', 'Extra-courses did', 'certifications',
       'workshops', 'talenttests taken?', 'olympiads',
       'reading and writing skills', 'memory capability score',
       'Interested subjects', 'interested career area ', 'Job/Higher Studies?',
       'Type of company want to settle in?',
       'Taken inputs from seniors or elders', 'interested in games',
       'Interested Type of Books', 'Salary Range Expected',
       'In a Realtionship?', 'Gentle or Tuff behaviour?',
       'Management or Technical', 'Salary/work', 'hard/smart worker',
       'worked in teams ever?', 'Introvert']

In [27]:
x1 = pd.DataFrame(df1, columns=headers)

In [28]:
x1.head()

Acedamic percentage in Operating Systems percentage in Algorithms  \
0                                  0.28509                 0.260299   
1                                  0.34998                 0.278189   
2                                 0.295012                 0.357339   
3                                 0.328025                 0.375503   
4                                 0.397157                 0.267649   

  Percentage in Programming Concepts Percentage in Software Engineering  \
0                           0.322276                           0.359461   
1                           0.327545                           0.269215   
2                           0.378115                           0.361494   
3                           0.258967                           0.362554   
4                           0.388523                           0.289234   

  Percentage in Computer Networks Percentage in Electronics Subjects  \
0                        0.388383                           0.388383   
1                        0.318571                           0.314085   
2                        0.253461                           0.336563   
3                        0.384135                           0.315077   
4                        0.306502                           0.384206   

  Percentage in Computer Architecture Percentage in Mathematics  \
0                            0.359461                  0.347066   
1                            0.327545                  0.376901   
2                            0.299168                  0.299168   
3                              0.2676                  0.379819   
4                            0.315136                  0.306502   

  Percentage in Communication skills Hours working per day  ...  \
0                           0.252036              0.037186  ...   
1                            0.40831              0.053843  ...   
2                            0.39058              0.045706  ...   
3                           0.297812              0.030213  ...   
4                           0.315136              0.017268  ...   

  interested in games Interested Type of Books Salary Range Expected  \
0                   0                       21                     1   
1                   1                        5                     1   
2                   1                       29                     0   
3                   0                       23                     0   
4                   1                        7                     1   

  In a Realtionship? Gentle or Tuff behaviour? Management or Technical  \
0                  0                         1                       0   
1                  1                         0                       1   
2                  0                         1                       0   
3                  1                         0                       0   
4                  0                         1                       0   

  Salary/work hard/smart worker worked in teams ever? Introvert  
0           0                 0                     1         0  
1           0                 0                     0         1  
2           1                 0                     0         1  
3           1                 1                     1         1  
4           1                 0                     1         1  

[5 rows x 38 columns]

In [29]:
label = labelencoder.fit_transform(label)
len(label)

20000

In [ ]:
label = dataset.iloc[:,-1].values

In [32]:
y = pd.DataFrame(label, columns=["Suggested Job Role"])
y

Suggested Job Role
0                       0
1                       1
2                       1
3                       2
4                       3
...                   ...
19995                  31
19996                  23
19997                   5
19998                  33
19999                  27

[20000 rows x 1 columns]

# 1. DECISION TREE CLASSIFIER

In [50]:
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import accuracy_score

In [37]:
x_train, x_test, y_train, y_test = train_test_split(x1, y, test_size=0.3, random_state=10)

In [51]:
len(x_train)

14000

In [52]:
len(x_test)

6000

In [53]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [54]:
classifier = tree.DecisionTreeClassifier()
classifier = classifier.fit(x_train, y_train)

In [55]:
y_pred = classifier.predict(x_test)

In [56]:
y_pred

array([28,  4, 24, ...,  4,  0, 28])

In [57]:
cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)

In [58]:
print("confusion matrix=", cm)
print()
print("accuracy=", accuracy*100)

confusion matrix= [[11  4  5 ...  3  8  8]
 [ 3  3  5 ...  5  5  7]
 [ 6  8  5 ...  2  7  2]
 ...
 [ 7  4  4 ...  8  5  4]
 [10  5  6 ...  5  3  1]
 [ 3  3  5 ...  6  5  8]]

accuracy= 3.0


# 1. 1. Decision Tree with entropy

In [45]:
entropy_classifier = tree.DecisionTreeClassifier(criterion = "entropy", random_state = 10)
entropy_classifier.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=10)

In [46]:
ent_y_pred = entropy_classifier.predict(x_test)

In [47]:
cm_entropy = confusion_matrix(y_test, ent_y_pred)

In [48]:
ent_acc = accuracy_score(y_test, ent_y_pred)

In [49]:
print("confusion matrix=", cm_entropy)
print()
print("accuracy=",ent_acc*100)

confusion matrix= [[ 7  7 10 ...  2  6  2]
 [ 4  5  2 ...  7  9  2]
 [ 7  6  3 ...  4  3  2]
 ...
 [ 3  5  9 ...  7  6  4]
 [ 7  6  5 ...  5  1 10]
 [ 4  3  6 ...  5  9  5]]

accuracy= 3.1


# 2. SVM classifier

In [33]:
from sklearn import svm

In [38]:
svm_clf = svm.SVC()
svm_clf.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC()

In [39]:
svm_y_pred = svm_clf.predict(x_test)

In [44]:
svm_y_pred

array([20, 20, 20, ..., 20, 20, 20])

In [42]:
cm_svm = confusion_matrix(y_test, svm_y_pred)
svm_acc = accuracy_score(y_test, svm_y_pred)

In [43]:
print("confusion matrics=",cm_svm)
print("  ")
print("accuracy=",svm_acc*100)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 5.75


In [ ]:
def preprocess(data):
    # Converting categorical data to numerical data
    label_encoder = LabelEncoder()
    for i in range(14, 38):
        data[:, i] = label_encoder.fit_transform(data[:, i])
    data1 = data[:, :14]
    normalized_data = Normalizer().fit_transform(data1)
    data2 = data[:, 14:]
    df1 = np.append(normalized_data, data2, axis=1)
    return df1

In [ ]:
import random
index = random.randint(0, len(dataset))
random_data = dataset.drop(['Suggested Job Role'], axis=1).iloc[index].values.reshape((1, 38))
true_value = dataset['Suggested Job Role'].iloc[index]
pred_value = svm_clf.predict(preprocess(random_data))
last_value = pred_value
while(pred_value == last_value):
  pred_value = svm_clf.predict(preprocess(random_data))
print(pred_value)

# 3. XGBOOST

In [69]:
from xgboost import XGBClassifier

In [70]:
xg_xtrain = pd.to_numeric(x_train.values.flatten())

In [71]:
xg_xtrain = xg_xtrain.reshape((14000,38))

In [72]:
model = XGBClassifier()
model.fit(xg_xtrain, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:98: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:133: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(objective='multi:softprob')

In [73]:
x_test.shape

(6000, 38)

In [74]:
xg_xtest = pd.to_numeric(x_test.values.flatten())

In [75]:
xg_xtest = xg_xtest.reshape((6000,38))

In [76]:
xgb_y_pred = model.predict(xg_xtest)

In [77]:
xgb_cm = confusion_matrix(y_test, xgb_y_pred)
xgb_acc = accuracy_score(y_test, xgb_y_pred)

In [78]:
print("confusion matrix=", xgb_cm)
print()
print("accuracy=", xgb_acc*100)

confusion matrix= [[4 6 3 ... 0 0 2]
 [5 4 1 ... 0 5 3]
 [2 5 0 ... 0 1 0]
 ...
 [2 4 0 ... 5 3 2]
 [1 8 3 ... 2 4 0]
 [1 3 2 ... 2 4 2]]

accuracy= 4.416666666666667


In [80]:
label_list[xgb_y_pred[0]], label_list[y_test.to_numpy()[2][0]]

('Network Security Administrator', 'E-Commerce Analyst')

In [81]:
type(y_test)

pandas.core.frame.DataFrame

In [82]:
len(xgb_y_pred), len(y_test)

(6000, 6000)

In [83]:
true_results = []
for i in range(len(y_test)):
  if xgb_y_pred[i] == y_test.values[i][0]:
    true_results.append(y_test.iloc[[i]].index[0])

In [84]:
len(true_results)

265

# 4. K Nearest Neighbours

In [85]:
from sklearn.neighbors import KNeighborsClassifier

In [86]:
knn_clf = KNeighborsClassifier()
knn_clf.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [87]:
knn_y_pred = knn_clf.predict(x_test)

In [88]:
knn_cm = confusion_matrix(y_test, knn_y_pred)
knn_acc = accuracy_score(y_test, knn_y_pred)

In [89]:
print("confusion matrix=", knn_cm)
print()
print("accuracy=", knn_acc*100)

confusion matrix= [[16 25 13 ...  0  1  1]
 [16 20 21 ...  1  4  0]
 [20 15 15 ...  0  1  1]
 ...
 [19 19 16 ...  0  0  3]
 [23 18 23 ...  0  1  1]
 [22 20 19 ...  0  0  1]]

accuracy= 3.1166666666666667


#5. Random Forest Classifier

In [90]:
from sklearn.ensemble import RandomForestClassifier
rfc_classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfc_classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [91]:
rfc_y_pred = rfc_classifier.predict(x_test)

In [92]:
rfc_cm = confusion_matrix(y_test, rfc_y_pred)
rfc_acc = accuracy_score(y_test, rfc_y_pred)

In [93]:
print("confusion matrix=", rfc_cm)
print()
print("accuracy=", rfc_acc*100)

confusion matrix= [[19 14 10 ...  2  0  1]
 [13 14 15 ...  4  1  4]
 [10 13  8 ...  2  7  5]
 ...
 [17 11 11 ...  8  0  4]
 [14 15 13 ...  1  3  3]
 [15 11  9 ...  5  1  1]]

accuracy= 3.183333333333333


# Dump Models

In [ ]:
models = [classifier, entropy_classifier, svm_clf, model, knn_clf, rfc_classifier]
names = ["dtc", "ent_dtc", "svm", "xgboost", "knn", "rfc"]
import pickle
for i in range(len(models)):
  print(f"Dumping {names[i]} model")
  pickle.dump(models[i], open(names[i] + ".pkl", "wb"))

Dumping dtc model
Dumping ent_dtc model
Dumping svm model
Dumping xgboost model
Dumping knn model
Dumping rfc model


In [ ]:
subjects = dataset["Interested subjects"].unique()

In [ ]:
subjects

array(['cloud computing', 'networks', 'hacking', 'Computer Architecture',
       'programming', 'parallel computing', 'IOT', 'data engineering',
       'Software Engineering', 'Management'], dtype=object)